name: API testing
run-name: ${{ github.actor }} is testing API code quality 🚀

on: [push]

jobs:
  testing:
    runs-on: python:3.11-slim
    steps:
     - uses: actions/checkout@v3
     - name: Install dependencies
       run: |
         pip install -r requirements.txt
     - name: Analysing the code with pylint
       run: |
         pylint api